# BeaconGUI Configuration File
# Complete Beacon GUI implementation for PocketMine-MP

# Effect update interval in ticks (20 ticks = 1 second)
# Default: 100 (5 seconds)
effect-update-interval: 100

# Beacon settings
beacon:
  # Maximum beacon range multiplier (default beacon range is 10 + level * 10)
  range-multiplier: 1.0
  
  # Enable beacon beam effects
  enable-beams: true
  
  # Beam update interval in ticks
  beam-update-interval: 40
  
  # Enable colored beams based on selected effects
  colored-beams: true
  
  # Enable enhanced effects (stronger than vanilla)
  enhanced-effects: false
  
  # Payment item requirements
  payment:
    # Require full stack for stronger effects
    require-full-stack: false
    
    # Item tier bonuses (multipliers for effect strength)
    tier-bonuses:
      iron: 1.0
      gold: 1.1
      emerald: 1.2
      diamond: 1.3
      netherite: 1.5

# Performance settings
performance:
  # Maximum beacons to process per tick
  max-beacons-per-tick: 10
  
  # Enable caching for beacon calculations
  enable-caching: true
  
  # Cache timeout in seconds
  cache-timeout: 30

# Debug settings
debug:
  # Enable debug logging
  enable-debug: false
  
  # Log beacon interactions
  log-interactions: false
  
  # Log effect applications
  log-effects: false